apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Without the resources-finalizer.argocd.argoproj.io finalizer, deleting an application will not delete the resources it manages.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: faces-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/buoyantio
    chart: faces-chart
    targetRevision: 1.5.0
  destination:
    namespace: faces
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
